print(11 * 10 * 1000, 'é uma representação do tipo integer.')
print(1.5 + 1 + 0.5, 'é uma representação do tipo float.')
print(True, 'é uma representação do tipo boolean.')
print(False, 'é uma representação do tipo boolean.')
print("Python", 'é uma representação de string, assim como o texto que acabas de ler.')
